### ISSUE TITLE
Unfold hierarchy : bug in the computed value for "number of clusters"

### ISSUE THREAD

**Issue by carinehue** [KhiopsML/kc-electron#102]
Data set : 1-Adult2varsEducationOccupation.khcj

Open several times the "Unfold hierarchy" dialog box (without asking any unfold)
-> the value of "Number of clusters" increases at each opening : 18 cluster at the first opening, 36 at the second and 54 at the third

![1-UnfoldHierarchy_1](https://github.com/KhiopsML/kc-electron/assets/101398951/f096b56e-c221-4c66-b24c-f9fa4c896438)
![1-UnfoldHierarchy_2](https://github.com/KhiopsML/kc-electron/assets/101398951/7401a371-8a28-4dc3-8e1f-cb152dd53e05)
![1-UnfoldHierarchy_3](https://github.com/KhiopsML/kc-electron/assets/101398951/1d933bed-735c-4e77-902f-2afaa8338e2e)

 - Platform: Windows
 - Version: 11.0.5

**Comment by carinehue** [comment]
Salut @stephanebouget :
J'obtiens ce bug dès que je clique deux fois de suite sur le bouton  "Unfold hierarchy"
C'est la valeur du Number of clusters maximal qui est modifiée. 
Cette valeur est celle utilisée en borne max au niveau de l'axe des abscisses des deux graphiques ou au niveau du bouton
pour régler la valeur du Number of clusters "courant"

Par exemple, j'ouvre le fichier 1-Adult avec 18 clusters.
1/ Je clique sur "Unfold hierarchy" une 1ère fois :  le number of clusters max sur l'axe des abscisses des 2 graphiques est à 18
2/Je clique sur Cancel
3/ Je reclique sur "Unfold hierarchy" : dans la fenêtre qui s'ouvre j'ai alors un number of cluster max de 36 sur les 2 graphiques
Si je recommence une 3ème fois, on passe de 36 à 54.

A l'étape 2/ si je clique sur Ok au lieu de Cancel ou si je modifie la valeur de number of cluster et que je clique sur ensuite sur Ok et Cancel, cela conduit également à l'étape 3/ à l'incrémentation du Number of clusters max

**Comment by carinehue** [comment]
oui.  pas toi ? je peux te montrer depuis mon poste si tu passes dans mon bureau

**Comment by carinehue** [comment]
> > Salut @stephanebouget : J'obtiens ce bug dès que je clique deux fois de suite sur le bouton "Unfold hierarchy" C'est la valeur du Number of clusters maximal qui est modifiée. Cette valeur est celle utilisée en borne max au niveau de l'axe des abscisses des deux graphiques ou au niveau du bouton pour régler la valeur du Number of clusters "courant"
> > Par exemple, j'ouvre le fichier 1-Adult avec 18 clusters. 1/ Je clique sur "Unfold hierarchy" une 1ère fois : le number of clusters max sur l'axe des abscisses des 2 graphiques est à 18 2/Je clique sur Cancel 3/ Je reclique sur "Unfold hierarchy" : dans la fenêtre qui s'ouvre j'ai alors un number of cluster max de 36 sur les 2 graphiques Si je recommence une 3ème fois, on passe de 36 à 54.
> > A l'étape 2/ si je clique sur Ok au lieu de Cancel ou si je modifie la valeur de number of cluster et que je clique sur ensuite sur Ok et Cancel, cela conduit également à l'étape 3/ à l'incrémentation du Number of clusters max
> 
> tu as ce comportement sur la 11.0.5 ?

oui, sur la 11.0.5 et a priori sur tous les jeux de données. Pas toi ? je peux te montrer depuis mon poste si tu passes dans mon bureau

**Comment by stephanebouget** [comment]
duplicated #98
