### ISSUE TITLE
External data : bug in update of external data when active line of the composition table is changed

### ISSUE THREAD

**Issue by carinehue** [KhiopsML/kc-electron#103]
DataSet with external data
1-Adult2varsEducationOccupation.khcj
1-ExternalData_JoinKeyEducation_DimensionEducation.txt

Activate the composition view.
Change from first line to third line in the composition table : the external data are not updated 

![UpdateExternalData](https://github.com/KhiopsML/kc-electron/assets/101398951/80e39f9b-c281-4976-bca2-bc413aa5bb97)

 - Platform: Windows
 - Version: 11.0.5

**Comment by stephanebouget** [comment]
also related to https://github.com/KhiopsML/kc-electron/issues/106
