### ISSUE TITLE
External data : not displayed if composition view is not activated

### ISSUE THREAD

**Issue by carinehue** [KhiopsML/kc-electron#104]
Dataset with external data
1-Adult2varsEducationOccupation.khcj
1-ExternalData_JoinKeyEducation_DimensionEducation.txt

Load external data with the composition view not activated : no external data displayed
Activate the composition view -> the external data are displayed
![LoadingExternalDataWithCompositionViewUnactivated](https://github.com/KhiopsML/kc-electron/assets/101398951/9bc85d63-2ace-4206-ba70-ae5417a38d1b)
![LoadingExternalDataWithCompositionViewActivated-](https://github.com/KhiopsML/kc-electron/assets/101398951/c336d2fc-1de7-4237-a5ab-163fb7d06c02)

 - Platform: Windows
 - Version: 11.0.5

**Comment by stephanebouget** [comment]
duplicate with https://github.com/KhiopsML/kc-electron/issues/89

**Comment by stephanebouget** [comment]
Une réflexion sur l’issue #104 :
L’absence d’affichage de données externes quand la composition view n’est pas active
Est compréhensible car justement tu n’as pas d’infos sur l’élément du cluster dont on voudrait afficher les données externes.

	Une solution serait  de modifier le texte du message qui actuellement est « No external data » pour afficher qqch
Du type « Add composition view to select the cluster element” 
	Ou alors forcer l’affichage de la vue composition quand des données externes ont été chargées.

Carine

**Comment by stephanebouget** [comment]
j'ai fait l'option 1 puisque dans le cas de l'option2 l'user a tjs la possibilité après de cacher la vue composition, ce qui reviendrait au pb initial
