### ISSUE TITLE
Select automatically the best unfolding : the matrix is not updated in some cases

### ISSUE THREAD

**Issue by carinehue** [KhiopsML/kc-electron#119]
1/ Open the coclustering 1-Adult2varsEducationOccupation.khcj
2/ Click on "Select automatically the best unfolding" (without performing any other actions before)
3/ Set "number of clusters" to 10 and click OK
-> the matrix is not updated

This bug does not occur if, before Step 1 and 2, you modify the selected cell by clicking either on the hierarchy, or on current clusters or in a cell of the matrix.
 
![UnfoldHierarchyWithoutMatrixUpdate](https://github.com/KhiopsML/kc-electron/assets/101398951/8f88341d-30e6-458c-9513-6dde81b70f33)

 - Platform: Windows
 - Version: 11.0.6

**Comment by stephanebouget** [comment]
lié à https://github.com/KhiopsML/kc-electron/issues/119
