### ISSUE TITLE
Display of current cluster table for first dimension

### ISSUE THREAD

**Issue by carinehue** [KhiopsML/kc-electron#127]
When activated, the "current cluster" view is no longer displayed for the first dimension
(this bug doesn't occur with 11.0.7)

![CurrentClusterFirstAxis-Empty](https://github.com/KhiopsML/kc-electron/assets/101398951/206e1e08-f41b-4b15-a966-1798c6459248)

**Platform / versions (please complete the following information):**
 - Platform: Windows
 - Version: 11.0.8

**Comment by stephanebouget** [comment]
@carinehue quel parcours utilisateur te permet d'arriver dans cette situation ? je n'arrive pas à reproduire

**Comment by carinehue** [comment]
Voici mon parcours : 

1/ Lancer KC
![Step1](https://github.com/KhiopsML/kc-electron/assets/101398951/0b48f3b5-bed7-4b56-a3c2-ac7cba0103c4)

2/ Open file 1-Adult2varsEducationOccupation.khcj
![Step2](https://github.com/KhiopsML/kc-electron/assets/101398951/d5407f66-983a-48d4-af9f-63431d904b6e)

3/ Open the view manager and activate all views
![Step3](https://github.com/KhiopsML/kc-electron/assets/101398951/388711a0-97c3-4190-9f2e-624c876f60a5)

4/ Save 
![Step4](https://github.com/KhiopsML/kc-electron/assets/101398951/8f200b6d-f370-469a-9c3c-bdcd9a05aa47)

**Comment by carinehue** [comment]
Autre observation 
un Copy Data de la fenêtre "vide"
![CopyData-EmptyView](https://github.com/KhiopsML/kc-electron/assets/101398951/4d08f18a-7fee-43d7-a774-b3d05542a0ba)

en donne son contenu : 
Current clusters
Name	Size	Frequency	Interest	
"{Prof-specialty, Armed-Forces}"	2	5800	1	
"{Exec-managerial}"	1	3973	0.678626	
"{Machine-op-inspct, Transport-moving, Handlers-cleaners}"	3	4689	0.720699	
"{Craft-repair}"	1	3937	0.516895	
"{Other-service}"	1	2977	0.468534	
"{Farming-fishing, Priv-house-serv}"	2	1047	0.24798	
"{Adm-clerical, Protective-serv}"	2	4280	0.447041	
"{Sales}"	1	3627	0.374934	
"{Tech-support}"	1	937	0.284324

**Comment by stephanebouget** [comment]
@carinehue je n'arrive pas à reproduire, je penses que tu es dans un cas spécifique qui bug. Tu pourrais me transmettre ce que tu as dans ton localstorage ?

pour cela tu ouvres les outils de dev:
![image](https://github.com/KhiopsML/kc-electron/assets/13203455/43c17827-1c61-4eef-9140-042a0f696b22)

en bas dans la console tu fais:
`console.log(localStorage);`

![image](https://github.com/KhiopsML/kc-electron/assets/13203455/c7e5aece-99b7-429b-afc1-83e39c0b0734)


et tu m'envoies le contenu:
![image](https://github.com/KhiopsML/kc-electron/assets/13203455/f620f79c-7f6a-48c6-865e-2abb18522312)

**Comment by carinehue** [comment]
@stephanebouget et voici ce que j'ai dans mon local storage :
{
    "KHIOPS_COVISUALIZATION_UUID": "67ce2a4133c846a6a63733b0fa74971a",
    "KHIOPS_COVISUALIZATION_SPLIT_SIZES": "{\"axisView\":{\"col\":[70,30],\"col0Row\":[50,50],\"col1Row\":[20,80],\"col0Row0Col\":[33.333333333333336,33.410249359365224,33.25641730730145],\"col0Row0Col2Row\":[24.50549450549451,75.49450549450549],\"col0Row1Col\":[25,25,25,25],\"col0Row1Col2Row\":[30,70]},\"contextView\":{\"col\":[70,30],\"col0Row0Col\":[25,25,25,25],\"col0Row0Col2Row\":[30,70]}}",
    "KHIOPS_COVISUALIZATION_VIEWS_LAYOUT": "{\"isDimensionsChecked\":true,\"isCoocurenceChecked\":true,\"dimensionsViewsLayoutsVO\":[{\"isChecked\":true,\"isHierarchyChecked\":true,\"isClustersChecked\":true,\"isAnnotationChecked\":true,\"isCompositionChecked\":true,\"isExternalDataChecked\":true,\"isDistributionChecked\":true,\"name\":\"occupation\"},{\"isChecked\":true,\"isHierarchyChecked\":true,\"isClustersChecked\":true,\"isAnnotationChecked\":true,\"isCompositionChecked\":true,\"isExternalDataChecked\":true,\"isDistributionChecked\":true,\"name\":\"education\"}]}",
    "KHIOPS_COVISUALIZATION_MODES_AG_GRID": "{\"selected-clusters-grid\":\"fitToSpace\",\"undefined\":\"fitToSpace\",\"cluster-composition-2\":\"fitToSpace\",\"cluster-composition-0\":\"fitToSpace\",\"cluster-composition-1\":\"fitToSpace\",\"cluster-details-grid-1\":\"fitToSpace\",\"cluster-details-grid-0\":\"fitToSpace\",\"cluster-details-grid-2\":\"fitToSpace\"}",
    "KHIOPS_COVISUALIZATION_OPEN_FILE": "{\"files\":[\"U:\\\\FamilleKhiops\\\\KhiopsCovizualisation\\\\SuiviCovizu\\\\PlanTestCovizu\\\\InputData\\\\1-Adult2varsEducationOccupation.khcj\",\"U:\\\\FamilleKhiops\\\\KhiopsCovizualisation\\\\SuiviCovizu\\\\PlanTestCovizu\\\\InputData\\\\7-AdultMissing.khcj\",\"U:\\\\FamilleKhiops\\\\KhiopsCovizualisation\\\\SuiviCovizu\\\\PlanTestCovizu\\\\InputData\\\\4-BugGillesExternalData.khcj\",\"U:\\\\FamilleKhiops\\\\KhiopsCovizualisation\\\\SuiviCovizu\\\\PlanTestCovizu\\\\InputData\\\\2-Iris3vars-Coclustering.khcj\",\"U:\\\\FamilleKhiops\\\\KhiopsCovizualisation\\\\SuiviCovizu\\\\PlanTestCovizu\\\\InputData\\\\3-Adult3vars.khcj\"]}",
    "KHIOPS_COVISUALIZATION_OPTIONS_AG_GRID_SEARCH_CLUSTER-DETAILS-GRID-0": "519",
    "KHIOPS_COVISUALIZATION_CELL_AG_GRID": "{\"cluster-composition-2\":{\"cluster\":164.54700000000003,\"typicality\":164,\"value\":164,\"frequency\":164},\"cluster-composition-0\":{\"cluster\":81.76600000000002,\"typicality\":80,\"value\":80,\"frequency\":80},\"cluster-details-grid-0\":{\"name\":148.88099999999997,\"size\":148,\"frequency\":148,\"interest\":148},\"cluster-composition-1\":{\"cluster\":58.35900000000001,\"typicality\":57,\"value\":57,\"frequency\":57},\"cluster-details-grid-2\":{\"name\":73.93599999999998,\"size\":72,\"frequency\":72,\"interest\":72},\"selected-clusters-grid\":{\"hierarchy\":170.32299999999998,\"shortDescription\":170,\"nbClusters\":170},\"cluster-details-grid-1\":{\"name\":24,\"size\":24,\"frequency\":24,\"interest\":24}}",
    "KHIOPS_COVISUALIZATION_COOKIE_CONSENT": "true",
    "KHIOPS_COVISUALIZATION_SETTING_MATRIX_CONTRAST": "0"
}

**Comment by stephanebouget** [comment]
@carinehue ah...

tu as une recherche encours sur ce tableau : 
![image](https://github.com/KhiopsML/kc-electron/assets/13203455/25ec0f7c-7aa4-44f4-996d-a16ca6891a37)

et comme à l'ouverture, la recherche est fermée, tu ne le vois pas.
je vais corriger ça : 
- je vais reseter les recherches à chaque changement de fichier
