### ISSUE TITLE
View manager behavior

### ISSUE THREAD

**Issue by stephanebouget** [KhiopsML/kc-electron#129]
" Comportement souhaité
## si dimensionsViewsLayoutsVO est présent dans le fichier
 on affiche les vues correspondantes
## sinon : que fait-on ?
- est-ce qu'on sauvegarde un état local de la dernière config de vue affichée ?
- est-ce qu'on affiche tjs les mêmes compsants ?
- autre ?

**Comment by carinehue** [comment]
@stephanebouget 
En cas d'absence de dimensionsViewsLayoutsVO présent dans le fichier, pourrait on afficher les vues selon un paramétrage qui serait précisé dans "Settings" ?
On ajouterait dans Settings une rubrique "Views manager" avec les choix d'activations Hierarchy / Current clusters / Annotation / etc.
Le setting par défaut du Views manager serait d'activer les deux axes avec leurs vues Hierarchy et Composition ainsi que les deux vues Dimensions et Co-occurence.

Rq sur les settings : 
que ce soit avec KhiopsVizu ou KhiopsCovizu, quand on change un élément du Settings et qu'on le save, le fichier qui était ouvert se ferme et on doit le ré-ouvrir. Est ce nécessaire pour le rafraichissement ?

**Comment by stephanebouget** [comment]
OK.

concernant : 

> Rq sur les settings :
> que ce soit avec KhiopsVizu ou KhiopsCovizu, quand on change un élément du Settings et qu'on le save, le fichier qui était ouvert se ferme et on doit le ré-ouvrir. Est ce nécessaire pour le rafraichissement ?

j'avais fait au + simple effectivement car c'est qqchose qu'on ne change pas souvent. mais je peux améliorer. 
cf. https://github.com/KhiopsML/kc-electron/issues/130

**Comment by carinehue** [comment]
@stephanebouget 

Je me demande si le sujet n'est pas plus large que celui du view manager et concerne globalement le comportement
souhaité en l'absence de "savedData".

Exemple : 
1/ je choisis de ne pas afficher la colonne "Size" du tableau "Current clusters" de la seconde variable
2/ je ferme l'outil sans sauvegarde
3/ je ré-ouvrer un fichier éventuellement différent du précédent : la colonne "Size" n'est plus affichée comme si le choix
que j'avais fait précédemment avait tout de même été stocké et conservé.

Dans la mesure où avec KhiopsCovizu, on permet à l'utilisateur de faire un "saveAs", j'aurais défini plutôt le comportement suivant 
A/ si présence de "savedData", prendre en compte les paramétrages des différents champs (viewLayout mais également Annotations, CollapsedNodes , etc)
B/ absence de "savedData" : affichage par défaut après reset des actions menées précédemment

Pour le cas particulier, du paramétrage à afficher, on peut peut-être déjà revenir à ce cas par défaut en l'absence de données sauvegardées.
Et voir ensuite si on ajoute la possibilité à l'utilisateur de sauvegarder ses choix dans un setting (je me dis que sinon on va être tenté de mettre beaucoup de choses dans Settings)

**Comment by stephanebouget** [comment]
Je ferme cette issue qui corrige :
A/ si présence de "savedData", prendre en compte les paramétrages des différents champs (viewLayout mais également Annotations, CollapsedNodes , etc)
B/ absence de "savedData" : affichage par défaut après reset des actions menées précédemment

et j'en ouvre une autre pour d'éventuelles améliorations futures : https://github.com/KhiopsML/kc-electron/issues/137
