### ISSUE TITLE
Statistics improvments

### ISSUE THREAD

**Issue by stephanebouget** [KhiopsML/kc-electron#133]
Je viens de tester le bouton « Statistics » accessible depuis le bouton (i) des panneau « Hierarchy ».
Cf. screenshot ci-dessous obtenu par « Copy image »

Voici quelques corrections et améliorations pour cette fonctionnalité :
•	Dans le cas d’une variable de type Categorical
- [x] 	Renommer « Interval » en « Cluster »
- [x] 	Renommer « Intervals » en « Clusters »
- [x] 	Ajouter une ligne 
« Values : <value number>» 
avant la ligne
« Frequency : <frequency> »
comportant le nombre de valeur du cluster en cours

•	Amélioration du « Copy image »

- [x]  Serait-il possible d’avoir un « Copy image » dédié pour la partie « Statistics » ?
o	Ou au moins qu’il reprenne le titre (« Hierachy occupation ») dans les deux cas, avec ou sans les statistics ?

![image](https://github.com/KhiopsML/kc-electron/assets/13203455/ef69989a-f5f5-4c73-a4a5-ed869d267a4d)

![image](https://github.com/KhiopsML/kc-electron/assets/13203455/2af0ca9a-c168-42c7-920a-d4aa59cfdf48)

**Comment by carinehue** [comment]
L'amélioration de la fonctionnalité 
"Ajouter une ligne « Values : » avant la ligne « Frequency : » comportant le nombre de valeur du cluster en cours" semble disponible uniquement quand on se trouve sur un cluster terminal.
Il faudrait l'ajouter également quand on est sur un cluster de la hiérarchie et afficher la somme des valeurs des clusters terminaux sous le cluster courant.
Exemple sur 1-Adult2varsEducationOccupation :
Afficher values = 4 si on est sur A13 car A13 contient 2 clusters terminaux, l'un avec 3 valeurs, le second avec une valeur.
![image](https://github.com/user-attachments/assets/246dd5b8-d58a-4d02-9cf4-680e3692ea30)

![image](https://github.com/user-attachments/assets/f3b6ee5a-41a5-4e0a-b4de-9242d90db008)
