### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by stephanebouget** [KhiopsML/kc-electron#136]
Au survol sur certains boutons/onglet, on a une infobulle d'explications. par exemple : 
![image](https://github.com/KhiopsML/khiops-visualization/assets/13203455/be5f6d64-1e26-4f2e-a2b3-d0c98f690364)

Pour certains elts, je n'ai pas trouvé l'info dans l'ancien code: 

## Onglets
![image](https://github.com/KhiopsML/khiops-visualization/assets/13203455/556284cd-7827-4a68-9106-ddee48403181)
TOOLTIPS.TABS.AXIS = 
TOOLTIPS.TABS.CONTEXT = 

## Current Clusters
![image](https://github.com/KhiopsML/khiops-visualization/assets/13203455/66f37bd1-34fa-4eb7-a36d-bff09271520d)
TOOLTIPS.AXIS.CURRENT_CLUSTERS.SIZE = 
TOOLTIPS.AXIS.CURRENT_CLUSTERS.HIERARCHICAL_LEVEL = 

## Composition
![image](https://github.com/KhiopsML/khiops-visualization/assets/13203455/134c573f-e798-4971-bc5c-f66fb8c311b3)
TOOLTIPS.AXIS.COMPOSITION.TYPICALITY = 

## Annotation
![image](https://github.com/KhiopsML/kc-electron/assets/13203455/437b5e2b-669f-4889-98d5-ef67a12310c5)
TOOLTIPS.AXIS.ANNOTATION.TITLE = 

## Selected cluster
![image](https://github.com/KhiopsML/kc-electron/assets/13203455/2453c690-c38a-4088-a196-ed449a0b0b01)
TOOLTIPS.AXIS.SELECTED_CLUSTERS.TITLE

**Comment by stephanebouget** [comment]
@carinehue pourrais tu me donner les définitions des infobulles correspondantes quand tu auras un moment ?

**Comment by carinehue** [comment]
@stephanebouget 

Voici les définitions :

**Onglets** 
TOOLTIPS.TABS.AXIS = "presents the coclustering"
TOOLTIPS.TABS.CONTEXT = "contextual dimensions of the coclustering (if more than 2 dimensions)"

**Current cluster**
TOOLTIPS.AXIS.CURRENT_CLUSTERS.SIZE = "the number of different items that belong to this cluster"
TOOLTIPS.AXIS.CURRENT_CLUSTERS.HIERARCHICAL_LEVEL = "normalized measure between 0 (all is folded) and 1 (all is unfolded); it represents the information kept for the current unfolding of the hierarchy and can be interpreted as a distance 
to the root cluster "

**Composition** 
TOOLTIPS.AXIS.COMPOSITION.TYPICALITY = "interest measure of the value within its cluster, between 0 (least representative) and 1 (most representative)"

**Annotation**
TOOLTIPS.AXIS.ANNOTATION.TITLE = "simple text box that allows annotating each cluster"

**Selected clusters**
TOOLTIPS.AXIS.SELECTED_CLUSTERS.TITLE = "global view of the state of the coclustering at the current level of unfolding"


Et en complément pour d'autres info-bulles vides :

**Distribution**
histogram of the distribution of a dimension on the selected cluster of the other dimension.

**External data**
"integrate external data associated to each cluster element. The selection of an item in the composition view display the corresponding data in this view. There are 3 types of data fields: textual, numerical and categorical. The display is optimized according to the data type. Several fields can be associated for each item."

**Co-occurence view**
Menu déroulant des critères : 
Frequency : number of occurences 
I (first_dim, second_dim) : mutual information
P(first_dim | second_dim) and P(second_dim | first_dim) : conditional probability
H(first_dim, second_dim)  : Hellinger distance

Cell stats (au dessus de la matrice)
F = : frequency : number of occurences in the selected co-cluster
EF = expected frequency in case of independence of the two dimensions
