### ISSUE TITLE
Coclustering with context : update axis name in criteria description above the co-occurence matrix

### ISSUE THREAD

**Issue by carinehue** [KhiopsML/kc-electron#141]
- Open a tri-clustering, for instance 2-Iris3vars-Coclustering.
- Change the context variable from Class to PetalLength

In the co-occurence matrix, the description of the criteria still contains PetalLength instead of Class.
![UpdateCriteriaNameWhenModifyingContextVariable](https://github.com/KhiopsML/kc-electron/assets/101398951/64f41c32-976e-4e27-88d1-6e3906e811c8)

 - Platform: Windows
 - Version: 11.0.9

**Comment by stephanebouget** [comment]
bien vu, c'est un bug qui remonte à quelques releases en plus
je regarde
