### ISSUE TITLE
Save current hierarchy as issue on information rate

### ISSUE THREAD

**Issue by stephanebouget** [KhiopsML/kc-electron#150]
- I load a large file 
- autounfold
- I save hierarchy as
- I reopen

there, the rank data of the clusters have not been updated which means that the useful information graph is constructed with missing data:

![image](https://github.com/KhiopsML/kc-electron/assets/13203455/4259f9f2-c583-41c7-bf56-779715aa8fef)

**Comment by carinehue** [comment]
@stephanebouget 

Could be linked to another problem with information rate (but without save current hierarchy)

- I load a small file without auto-unfold and 18 clusters
- I fold the coclustering to 10 clusters with "Select automatically the best unfolding" : the information rate for 10 clusters is equal to 93,2%
![InformationRate-SeuilTechnique-AvantOKDepliement-1Adult](https://github.com/KhiopsML/kc-electron/assets/101398951/b920e6c8-85b9-461a-a70a-05d6ab71bae3)
- click Ok 
- I re-open the "Select automatically the best unfolding" : the displayed information rate for 10 clusters is 100%
![InformationRate-SeuilTechnique-ReouvertureDepliement-1Adult](https://github.com/KhiopsML/kc-electron/assets/101398951/ceac5f92-05f6-4c50-9bf1-382a573efe60)
