### ISSUE TITLE
Zero exception broken on covisualization

### ISSUE THREAD

**Issue by khiopsrelease** [KhiopsML/kc-electron#60]
![image](https://github.com/khiopsrelease/kc-release/assets/50991455/d658be8d-cec8-49cb-b6a1-1cdf0b5550d9)

Attention sur KV c'est OK: 
![image](https://github.com/khiopsrelease/kc-release/assets/50991455/d7c54a48-9fb2-41cb-bd2e-90a7be8873f4)

**Comment by stephanebouget** [comment]
@carinehue je me rend compte que c'est le cas depuis très longtemps, cette feature a t'elle un intérêt dans covisu ?

**Comment by stephanebouget** [comment]
bouton caché dans covisu
